stages:
  - build_bin

build_bin:
  image: ubuntu:xenial
  stage: build_bin
  script:
    # install required tools
    - apt-get update && apt-get install -y git make
    - https://sh.rustup.rs -sSf | sh
    # install openssl
    - git clone git://git.openssl.org/openssl.git && \
        cd openssl && \
        ./config && \
        make && make install
    # build binary
    - cargo build --release
  artifacts:
    paths:
      - target/release/paste_nc
