stages:
  - build_bin

build_bin:
  image: ubuntu:xenial
  stage: build_bin
  script:
    # install required tools
    - apt-get update && apt-get install -y git make curl gcc pkg-config libssl-dev
    - curl https://sh.rustup.rs -sSf > rustup.sh
    - chmod +x rustup.sh
    - ./rustup.sh -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    # install openssl
    - git clone git://git.openssl.org/openssl.git
    - cd openssl
    - ./config
    - make && make install
    - mkdir lib
    - cp *.so* lib
    - export OPENSSL_DIR=$(pwd)
    - export OPENSSL_STATIC=$(pwd) # link statically
    - cd ..
    # build binary
    - cargo build --release
  artifacts:
    paths:
      - target/release/paste_nc
