stages:
  - build_bin

build_bin:
  image: ubuntu:xenial
  stage: build_bin
  script:
    # install required tools
    # maybe add libssl-dev
    - apt-get update && apt-get install -y git make curl gcc pkg-config
    - curl https://sh.rustup.rs -sSf > rustup.sh
    - chmod +x rustup.sh
    - ./rustup.sh -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    # install openssl
    - git clone git://git.openssl.org/openssl.git
    - cd openssl
    - ./config
    - make && make install
    - export OPENSSL_INCLUDE_DIR=$(pwd)/include/openssl
    - export OPENSSL_LIB_DIR=$(pwd)/lib
    - ls $OPENSSL_LIB_DIR
    # build binary
    - cargo build --release
  artifacts:
    paths:
      - target/release/paste_nc
