[package]
name = "paste_nc"
version = "0.1.0"
authors = ["Nikita Volobuev <nikitavbv@gmail.com>"]
edition = "2018"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = "0.9.5"
serde_json = "1.0"